version: "3.7"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=coda
    ports:
      - "127.0.0.1:54320:5432"
    volumes:
      - ./coda-postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  coda:
    image: codaprotocol/coda-demo:0.0.12-beta-demo-mode-sync-status-a6de071
    container_name: "coda"
    command: ""
    ports:
      - "8302:8302"
      - "8303:8303"
    volumes:
      - ./coda-node-data:/root/
  frontend:
    image: gobitfly/coda-explorer:latest
    command: ./frontend -dbHost postgres -dbUser postgres -dbName coda -dbPassword postgres -dbPort 5432
    ports:
      - "127.0.0.1:3333:3333"
    restart: always
    labels:
      - "traefik.enable=true"
  indexer:
    image: gobitfly/coda-explorer:latest
    command: ./indexer -dbHost postgres -dbUser postgres -dbName coda -dbPassword postgres -dbPort 5432 -coda coda:3085/graphql
    restart: always